# Generated by Django 4.2.6 on 2023-10-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=20)),
                ('surname', models.CharField(help_text='Фамилия', max_length=20)),
                ('fatherName', models.CharField(help_text='Отчество', max_length=20)),
                ('birthday', models.DateField()),
                ('region', models.CharField(help_text='Область', max_length=20)),
                ('street', models.CharField(help_text='Улица', max_length=20)),
                ('home', models.CharField(help_text='Дом', max_length=20)),
                ('flat', models.CharField(help_text='Квартира', max_length=20)),
                ('phone', models.IntegerField(help_text='Номер телефона', max_length=12)),
                ('vk', models.CharField(help_text='ВК-ID', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mladoServer.personaldata')),
            ],
        ),
    ]
