# Generated by Django 4.2.6 on 2023-10-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mladoServer', '0003_personaldata_permission_alter_registerlist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='vk_id',
            field=models.CharField(default='clear', help_text='непонятная хуй2ня', max_length=20),
        ),
    ]
